// <copyright file="ContractSamples.cs" company="ITANEO">
// Copyright (c) ITANEO. All rights reserved.
// Licensed under the MIT License.
// </copyright>

using Hexalith.Conversations.Contracts.Commands;
using Hexalith.Conversations.Contracts.Conformance;
using Hexalith.Conversations.Contracts.Diagnostics;
using Hexalith.Conversations.Contracts.Errors;
using Hexalith.Conversations.Contracts.Events;
using Hexalith.Conversations.Contracts.Governance;
using Hexalith.Conversations.Contracts.Identifiers;
using Hexalith.Conversations.Contracts.Participants;
using Hexalith.Conversations.Contracts.Projections;
using Hexalith.Conversations.Contracts.Queries;
using Hexalith.Conversations.Contracts.Results;
using Hexalith.Conversations.Contracts.TrustStates;
using Hexalith.Conversations.Contracts.Versioning;

namespace Hexalith.Conversations.Contracts.Tests;

internal static class ContractSamples
{
    internal static readonly SchemaVersion Version = new(1);
    internal static readonly TenantId Tenant = new("tenant-001");
    internal static readonly ConversationId Conversation = new("conversation-001");
    internal static readonly PartyId Actor = new("party-actor");
    internal static readonly PartyId Participant = new("party-participant");
    internal static readonly MessageId Message = new("message-001");
    internal static readonly ProjectId Project = new("project-001");
    internal static readonly FolderId Folder = new("folder-001");
    internal static readonly FileId File = new("file-001");
    internal static readonly BusinessReference Business = new("crm", "case-123");

    internal static readonly ProviderCorrelationMetadata ProviderCorrelation = new(
        "provider-a",
        "assistant",
        Version,
        "session-reference",
        "response-reference",
        new Dictionary<string, string>
        {
            ["region"] = "eu",
        });

    internal static readonly CallerMetadata Caller = new(
        Version,
        "adopter-client",
        "1.4.0",
        "front-composer",
        "adopter-portal",
        "intake",
        new Dictionary<string, string>
        {
            ["channel"] = "web",
        });

    internal static readonly ConversationCommandMetadata CommandMetadata = new(
        Version,
        Tenant,
        Actor,
        "correlation-001",
        "causation-001",
        "idempotency-001");

    internal static readonly ConversationEventMetadata EventMetadata = new(
        Version,
        "event-001",
        ConversationEventType.ConversationCreated,
        Tenant,
        Conversation,
        "correlation-001",
        new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
        Actor,
        "causation-001");

    internal static readonly ConversationEventMetadata EventMetadataWithoutCausation = new(
        Version,
        "event-002",
        ConversationEventType.ConversationCreated,
        Tenant,
        Conversation,
        "correlation-002",
        new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
        Actor);

    internal static readonly ConversationEventMetadata ParticipantEventMetadata = new(
        Version,
        "event-participant-001",
        ConversationEventType.ParticipantAdded,
        Tenant,
        Conversation,
        "correlation-001",
        new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
        Actor,
        "causation-001");

    internal static readonly ConversationEventMetadata LifecycleChangedEventMetadata = new(
        Version,
        "event-lifecycle-001",
        ConversationEventType.ConversationLifecycleChanged,
        Tenant,
        Conversation,
        "correlation-001",
        new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
        Actor,
        "causation-001");

    internal static readonly ProjectionFreshness Freshness = new(
        ProjectionTrustState.Current,
        new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
        Version,
        "Visible after accepted writes are projected.");

    internal static readonly ProjectionFreshnessV1 FreshnessV1 = new(
        Version,
        "pos:0000000042",
        42,
        new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
        new DateTimeOffset(2026, 5, 18, 11, 0, 5, TimeSpan.Zero),
        TimeSpan.FromSeconds(5),
        IsStale: false,
        ProjectionTrustState.Current,
        ProjectionFreshnessReasonCode.Current);

    internal static readonly ReadModelVisibility Visibility = new(
        ProjectionTrustState.Stale,
        "Read models may lag immediately after command acceptance.");

    internal static readonly DateTimeOffset GovernanceTimestamp = new(2026, 5, 18, 12, 0, 0, TimeSpan.Zero);

    internal static readonly GovernanceOperationMetadata GovernanceMetadata = new(
        Version,
        Tenant,
        Conversation,
        Actor,
        "customer-request",
        "retention-policy-standard",
        GovernanceTimestamp,
        "correlation-001",
        "causation-001");

    internal static readonly GovernanceTarget GovernanceConversationTarget = new(GovernedTargetKind.Conversation);

    internal static readonly GovernanceTarget SensitivityMessageTarget = new(GovernedTargetKind.Message, MessageId: Message);

    internal static readonly GovernanceTarget RedactionMessageTarget = new(GovernedTargetKind.Message, MessageId: Message);

    internal static readonly GovernanceAuditEvidenceReference AuditEvidence = new(
        new AuditEvidenceHandle("audit-evidence-001"),
        "retention-policy-standard",
        GovernanceTimestamp);

    internal static readonly PrivilegedOperationalJustificationV1 PrivilegedJustification = new(
        Version,
        Tenant,
        Conversation,
        GovernanceConversationTarget,
        Actor,
        PrivilegedOperationalActionClass.Read,
        PrivilegedActionClass.ComplianceReview,
        "privileged-review-policy",
        "customer-request",
        GovernanceTimestamp,
        "correlation-001",
        "causation-001",
        AuditEvidence);

    internal static readonly GovernanceRequest GovernanceRequest = new(
        GovernanceMetadata,
        GovernanceOperationKind.SetRetentionPolicy,
        GovernanceConversationTarget,
        RetentionAction.ApplyPolicy);

    internal static readonly SetConversationRetentionPolicyCommand RetentionCommand = new(
        CommandMetadata,
        Conversation,
        "retention-policy-standard",
        "customer-request",
        GovernanceTimestamp);

    internal static readonly MarkConversationContentSensitiveCommand SensitivityCommand = new(
        CommandMetadata,
        Conversation,
        SensitivityMessageTarget,
        SensitivityCategory.Restricted,
        "sensitivity-policy-standard",
        "customer-request",
        GovernanceTimestamp);

    internal static readonly RedactMessageContentCommand RedactionCommand = new(
        CommandMetadata,
        Conversation,
        RedactionMessageTarget,
        RedactionCategory.ContentSuppression,
        "redaction-policy-standard",
        "customer-request",
        GovernanceTimestamp);

    internal static readonly ConversationEventMetadata RetentionSetEventMetadata = new(
        Version,
        "event-retention-set-001",
        ConversationEventType.RetentionPolicySet,
        Tenant,
        Conversation,
        "correlation-001",
        GovernanceTimestamp,
        Actor,
        "causation-001");

    internal static readonly ConversationEventMetadata RetentionReplacedEventMetadata = new(
        Version,
        "event-retention-replaced-001",
        ConversationEventType.RetentionPolicyReplaced,
        Tenant,
        Conversation,
        "correlation-001",
        GovernanceTimestamp.AddMinutes(1),
        Actor,
        "causation-001");

    internal static readonly ConversationEventMetadata SensitivityMarkedEventMetadata = new(
        Version,
        "event-sensitive-marked-001",
        ConversationEventType.ConversationContentMarkedSensitive,
        Tenant,
        Conversation,
        "correlation-001",
        GovernanceTimestamp,
        Actor,
        "causation-001");

    internal static readonly ConversationEventMetadata RedactionEventMetadata = new(
        Version,
        "event-redacted-001",
        ConversationEventType.MessageContentRedacted,
        Tenant,
        Conversation,
        "correlation-001",
        GovernanceTimestamp,
        Actor,
        "causation-001");

    internal static IReadOnlyList<object> AllContracts =>
    [
        Version,
        new ContractVersionInfo("Conversations", Version, Version),
        new UnsupportedSchemaVersion(new SchemaVersion(2), Version, Version),
        ContractCompatibilityStatus.Supported,
        ContractCompatibilityStatus.Deprecated,
        ContractCompatibilityStatus.Unsupported,
        ContractCompatibilityStatus.Invalid,
        new ContractPackageVersionInfo("Hexalith.Conversations.Contracts", "1.0.0"),
        new ContractCompatibilityRemediation(
            "upgrade-to-active-v1",
            new Uri("https://docs.hexalith.local/conversations/contracts/v1/compatibility")),
        new ContractCompatibilityRequest(
            CommandSchemaVersion: "1",
            ProjectionSchemaVersion: "1",
            EventSchemaVersion: "1",
            ContractsPackageVersion: "1.0.0",
            ClientPackageVersion: "1.0.0"),
        ConversationContractCompatibility.Current,
        ConversationContractCompatibility.Evaluate(new ContractCompatibilityRequest(
            CommandSchemaVersion: "1",
            ProjectionSchemaVersion: "1",
            EventSchemaVersion: "1",
            ContractsPackageVersion: "1.0.0",
            ClientPackageVersion: "1.0.0")),
        ConversationContractCompatibility.Evaluate(new ContractCompatibilityRequest(ContractsPackageVersion: "0.9.0")),
        ConversationContractCompatibility.Evaluate(new ContractCompatibilityRequest(CommandSchemaVersion: "2")),
        ConversationContractCompatibility.Evaluate(new ContractCompatibilityRequest(EventSchemaVersion: "latest")),
        OnboardingDiagnosticCheck.TenantContext,
        OnboardingDiagnosticStatus.Ready,
        ConversationCorePreconditionCatalog.Get("projection-freshness"),
        new OnboardingDiagnosticCheckResultV1(
            Version,
            OnboardingDiagnosticCheck.TenantContext,
            OnboardingDiagnosticStatus.Ready,
            "Tenant context is current and access is allowed.",
            "none",
            new Uri("https://docs.hexalith.local/conversations/contracts/v1/preconditions"),
            ["AC1", "AC2"]),
        new OnboardingDiagnosticCheckResultV1(
            Version,
            OnboardingDiagnosticCheck.ProjectionSubscription,
            OnboardingDiagnosticStatus.Degraded,
            "Tenant projection is not current; retry after it is refreshed.",
            "retry-after-projection-current",
            new Uri("https://docs.hexalith.local/conversations/contracts/v1/preconditions"),
            ["AC2", "AC3"],
            ConversationErrorCatalog.CreateError(ConversationErrorCode.TenantProjectionStale, "correlation-001")),
        new OnboardingDiagnosticRunResultV1(
            Version,
            OnboardingDiagnosticStatus.Degraded,
            "Some CORE preconditions are not yet ready.",
            "correlation-001",
            new DateTimeOffset(2026, 5, 23, 12, 0, 0, TimeSpan.Zero),
            [
                new OnboardingDiagnosticCheckResultV1(
                    Version,
                    OnboardingDiagnosticCheck.TenantContext,
                    OnboardingDiagnosticStatus.Ready,
                    "Tenant context is current and access is allowed.",
                    "none",
                    new Uri("https://docs.hexalith.local/conversations/contracts/v1/preconditions"),
                    ["AC2"]),
                new OnboardingDiagnosticCheckResultV1(
                    Version,
                    OnboardingDiagnosticCheck.AuditAvailability,
                    OnboardingDiagnosticStatus.Degraded,
                    "Audit recording is not currently available; retry later.",
                    "retry-after-audit-available",
                    new Uri("https://docs.hexalith.local/conversations/contracts/v1/preconditions"),
                    ["AC2", "AC3"],
                    ConversationErrorCatalog.CreateError(ConversationErrorCode.AuditSinkUnavailable, "correlation-001")),
            ]),
        ReleaseGateStatus.Pass,
        ReleaseGateStatus.Fail,
        ReleaseGateStatus.Waived,
        ReleaseGateStatus.UnknownAccepted,
        ReleaseGateId.TenantIsolation,
        ReleaseGateId.ProviderPortability,
        new ReleaseGateResultV1(
            ReleaseGateId.TenantIsolation,
            ReleaseGateStatus.Pass,
            "Gate result evidence verified.",
            "isolation-evidence-001",
            new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero),
            "FR86"),
        new ReleaseGateResultV1(
            ReleaseGateId.ProviderPortability,
            ReleaseGateStatus.UnknownAccepted,
            "No direct adopter suite coverage; full proof suite deferred.",
            "portability-stub-001",
            new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero),
            "FR86"),
        new ReleaseConformanceArtifactV1(
            new SchemaVersion(1),
            "ci-build-sample",
            "conformance-runner",
            "test-env-local",
            "synthetic-dataset",
            "1032 tests",
            "release-manifest-stub",
            new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero),
            [new SchemaVersion(1)],
            ["hexalith-conversations-contracts-1.0.0"],
            ["correlation-conformance-run"],
            [
                new ReleaseGateResultV1(ReleaseGateId.TenantIsolation, ReleaseGateStatus.UnknownAccepted, "Partial adopter coverage; full suite deferred.", "isolation-evidence-001", new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero), "FR86"),
                new ReleaseGateResultV1(ReleaseGateId.AuditIntegrity, ReleaseGateStatus.Pass, "Governance precondition check passed.", "audit-integrity-evidence", new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero), "FR86"),
                new ReleaseGateResultV1(ReleaseGateId.RedactionNonLeakage, ReleaseGateStatus.UnknownAccepted, "Partial adopter coverage; full suite deferred.", "redaction-non-leakage-stub", new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero), "FR86"),
                new ReleaseGateResultV1(ReleaseGateId.UnsupportedSchemaRejection, ReleaseGateStatus.UnknownAccepted, "Partial adopter coverage; full suite deferred.", "schema-rejection-evidence", new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero), "FR86"),
                new ReleaseGateResultV1(ReleaseGateId.ProjectionRebuildDeterminism, ReleaseGateStatus.UnknownAccepted, "Partial adopter coverage; full suite deferred.", "rebuild-determinism-evidence", new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero), "FR86"),
                new ReleaseGateResultV1(ReleaseGateId.ContractCompatibility, ReleaseGateStatus.UnknownAccepted, "Partial adopter coverage; full manifest deferred.", "compatibility-evidence-001", new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero), "FR86"),
                new ReleaseGateResultV1(ReleaseGateId.ProviderPortability, ReleaseGateStatus.UnknownAccepted, "No direct adopter suite coverage; full suite deferred.", "portability-stub-001", new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero), "FR86"),
            ]),
        ConformanceCheck.CreateConversation,
        ConformanceOutcome.Ready,
        ConformanceFailureClassification.Conformant,
        new ConformanceCheckResultV1(
            Version,
            ConformanceCheck.CreateConversation,
            "supported",
            ConformanceOutcome.Ready,
            ConformanceFailureClassification.Conformant,
            ["FR73", "FR74"],
            ["supported-schema-versions"],
            ["release-gate-commands-queries-events"],
            "Create conversation accepted the supported request and projected current evidence.",
            "none",
            new Uri("https://docs.hexalith.local/conversations/contracts/v1/conformance"),
            "conformance-create-conversation"),
        new ConformanceCheckResultV1(
            Version,
            ConformanceCheck.CompatibilityDiscovery,
            "unsupported",
            ConformanceOutcome.Blocked,
            ConformanceFailureClassification.ProductInvariant,
            ["FR74"],
            ["contract-compatibility"],
            ["release-gate-version-discovery"],
            "Unsupported version discovery returned a typed versioning error rather than processing under an incompatible contract.",
            "use-supported-v1-package",
            new Uri("https://docs.hexalith.local/conversations/contracts/v1/conformance"),
            "conformance-compatibility-discovery",
            ConversationErrorCatalog.CreateError(ConversationErrorCode.SchemaVersionUnsupported, "conformance-compatibility-discovery")),
        new ConformanceRunResultV1(
            Version,
            ConformanceOutcome.Ready,
            ConformanceFailureClassification.Conformant,
            "All CORE conformance checks passed against the synthetic fixture.",
            "adopter-core-conformance-v1",
            "conformance-runner",
            "correlation-conformance-001",
            new DateTimeOffset(2026, 5, 23, 9, 0, 0, TimeSpan.Zero),
            [
                new ConformanceCheckResultV1(
                    Version,
                    ConformanceCheck.TenantBinding,
                    "supported",
                    ConformanceOutcome.Ready,
                    ConformanceFailureClassification.Conformant,
                    ["FR74"],
                    ["projection-freshness"],
                    ["release-gate-tenant-isolation"],
                    "Tenant binding scoped the read to the authorized tenant.",
                    "none",
                    new Uri("https://docs.hexalith.local/conversations/contracts/v1/conformance"),
                    "correlation-conformance-tenantbinding"),
            ]),
        ConversationCommandType.CreateConversationCommand,
        ConversationCommandType.SetConversationRetentionPolicyCommand,
        ConversationCommandType.MarkConversationContentSensitiveCommand,
        ConversationCommandType.RedactMessageContentCommand,
        ConversationEventType.ConversationCreated,
        ConversationEventType.RetentionPolicySet,
        ConversationEventType.ConversationContentMarkedSensitive,
        ConversationEventType.MessageContentRedacted,
        ConversationLifecycleStatus.Open,
        ParticipantType.Human,
        ParticipantRole.Member,
        ConversationErrorCode.TenantIsolationViolation,
        ConversationErrorCategory.Authorization,
        ConversationErrorClientAction.CheckAccess,
        ConversationErrorCatalog.Get(ConversationErrorCode.TenantIsolationViolation),
        Tenant,
        Conversation,
        Actor,
        Project,
        Folder,
        File,
        Message,
        Business,
        ProviderCorrelation,
        Caller,
        CommandMetadata,
        GovernanceOperationKind.SetRetentionPolicy,
        GovernedTargetKind.Conversation,
        RetentionAction.ApplyPolicy,
        SensitivityCategory.Sensitive,
        RedactionCategory.DisplayMask,
        ArchivalState.Archived,
        LegalHoldDeferral.DeferredUntilRelease,
        PolicyBlockedOutcome.LegalHoldActive,
        PrivilegedActionClass.OperationalOverride,
        PrivilegedOperationalActionClass.Read,
        GovernanceOutcome.Succeeded,
        GovernanceRemediation.None,
        GovernanceStateConcept.EventHistory,
        ConversationGovernanceVerificationScopeKind.Conversation,
        ConversationGovernanceVerificationSuite.AuditPairing,
        ConversationGovernanceVerificationExecutionStatus.Completed,
        ConversationGovernanceVerificationFailureClassification.Passed,
        ConversationGovernanceVerificationRemediation.None,
        AuditRecordActionClassification.Allowed,
        BuyerAcceptanceDemoStepKind.Find,
        BuyerAcceptanceDemoFixtureKind.FullTrust,
        BuyerAcceptanceDemoTrustState.Current,
        BuyerAcceptanceEvidenceOwnership.Module,
        BuyerAcceptanceDemoExecutionStatus.Passed,
        new ConversationGovernanceVerificationEvidenceHandle("verification-proof-001"),
        new BuyerAcceptanceDemoFixtureV1(
            Version,
            Tenant,
            "fixture-full",
            BuyerAcceptanceDemoFixtureKind.FullTrust,
            BuyerAcceptanceDemoTrustState.Current,
            "synthetic-demo-data",
            "Synthetic governed conversation",
            "Continue with governed evidence.",
            Conversation,
            ["AC1", "AC2"]),
        new BuyerAcceptanceDemoStepV1(
            Version,
            "step-find",
            BuyerAcceptanceDemoStepKind.Find,
            BuyerAcceptanceDemoFixtureKind.FullTrust,
            BuyerAcceptanceDemoTrustState.Current,
            "Review governed evidence",
            "Continue with governed evidence.",
            ["AC1", "AC5"],
            Conversation,
            Business,
            "message:message-001",
            AuditEvidence.Handle,
            EvidenceHandles: [new ConversationGovernanceVerificationEvidenceHandle("verification-proof-001")]),
        new BuyerAcceptanceDemoScenarioV1(
            Version,
            Tenant,
            "buyer-acceptance-demo-v1",
            "synthetic-demo-data",
            "Buyer acceptance demo",
            "correlation-001",
            [
                new BuyerAcceptanceDemoFixtureV1(
                    Version,
                    Tenant,
                    "fixture-full",
                    BuyerAcceptanceDemoFixtureKind.FullTrust,
                    BuyerAcceptanceDemoTrustState.Current,
                    "synthetic-demo-data",
                    "Synthetic governed conversation",
                    "Continue with governed evidence.",
                    Conversation,
                    ["AC1", "AC2"]),
            ],
            [
                new BuyerAcceptanceDemoStepV1(
                    Version,
                    "step-find",
                    BuyerAcceptanceDemoStepKind.Find,
                    BuyerAcceptanceDemoFixtureKind.FullTrust,
                    BuyerAcceptanceDemoTrustState.Current,
                    "Review governed evidence",
                    "Continue with governed evidence.",
                    ["AC1", "AC5"],
                    Conversation,
                    Business,
                    "message:message-001",
                    AuditEvidence.Handle,
                    EvidenceHandles: [new ConversationGovernanceVerificationEvidenceHandle("verification-proof-001")]),
            ],
            ["AC1", "AC2", "AC3", "AC4", "AC5"]),
        new BuyerAcceptanceEvidenceStepResultV1(
            Version,
            "step-find",
            BuyerAcceptanceDemoStepKind.Find,
            BuyerAcceptanceDemoExecutionStatus.Passed,
            BuyerAcceptanceDemoTrustState.Current,
            BuyerAcceptanceEvidenceOwnership.Module,
            "Step passed.",
            "Continue with governed evidence.",
            ["AC1", "AC5"],
            [new ConversationGovernanceVerificationEvidenceHandle("verification-proof-001")]),
        new BuyerAcceptanceVerificationSummaryV1(
            Version,
            ConversationGovernanceVerificationSuite.TenantIsolation,
            ConversationGovernanceVerificationExecutionStatus.Completed,
            ConversationGovernanceVerificationFailureClassification.Passed,
            "Trusted scope matches derived records.",
            ConversationGovernanceVerificationRemediation.None,
            ["AC1", "AC5"]),
        new BuyerAcceptanceEvidenceSummaryV1(
            Version,
            Tenant,
            "buyer-acceptance-demo-v1",
            "synthetic-demo-data",
            GovernanceTimestamp,
            "runner-001",
            "correlation-001",
            BuyerAcceptanceDemoExecutionStatus.Passed,
            [
                new BuyerAcceptanceEvidenceStepResultV1(
                    Version,
                    "step-find",
                    BuyerAcceptanceDemoStepKind.Find,
                    BuyerAcceptanceDemoExecutionStatus.Passed,
                    BuyerAcceptanceDemoTrustState.Current,
                    BuyerAcceptanceEvidenceOwnership.Module,
                    "Step passed.",
                    "Continue with governed evidence.",
                    ["AC1", "AC5"],
                    [new ConversationGovernanceVerificationEvidenceHandle("verification-proof-001")]),
            ],
            [
                new BuyerAcceptanceVerificationSummaryV1(
                    Version,
                    ConversationGovernanceVerificationSuite.TenantIsolation,
                    ConversationGovernanceVerificationExecutionStatus.Completed,
                    ConversationGovernanceVerificationFailureClassification.Passed,
                    "Trusted scope matches derived records.",
                    ConversationGovernanceVerificationRemediation.None,
                    ["AC1", "AC5"]),
            ],
            ["AC1", "AC2", "AC3", "AC4", "AC5"],
            "Buyer acceptance demo passed.",
            [BuyerAcceptanceEvidenceOwnership.Module, BuyerAcceptanceEvidenceOwnership.InheritedPlatformControl]),
        new ConversationGovernanceVerificationScopeV1(
            Version,
            ConversationGovernanceVerificationScopeKind.Conversation,
            Tenant,
            Conversation,
            new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
            new DateTimeOffset(2026, 5, 18, 12, 0, 0, TimeSpan.Zero)),
        new ConversationGovernanceVerificationRequestV1(
            Version,
            new ConversationGovernanceVerificationScopeV1(
                Version,
                ConversationGovernanceVerificationScopeKind.Conversation,
                Tenant,
                Conversation,
                new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
                new DateTimeOffset(2026, 5, 18, 12, 0, 0, TimeSpan.Zero)),
            [ConversationGovernanceVerificationSuite.AuditPairing, ConversationGovernanceVerificationSuite.TenantIsolation],
            "correlation-001"),
        new ConversationGovernanceVerificationCheckResultV1(
            Version,
            ConversationGovernanceVerificationSuite.AuditPairing,
            "audit-pairing",
            ["AC1", "AC5"],
            ConversationGovernanceVerificationExecutionStatus.Completed,
            ConversationGovernanceVerificationFailureClassification.Passed,
            "Governed state has paired audit references.",
            ConversationGovernanceVerificationRemediation.None,
            new ConversationGovernanceVerificationEvidenceHandle("verification-proof-001")),
        new ConversationGovernanceVerificationRunResultV1(
            Version,
            new ConversationGovernanceVerificationScopeV1(
                Version,
                ConversationGovernanceVerificationScopeKind.Conversation,
                Tenant,
                Conversation,
                new DateTimeOffset(2026, 5, 18, 11, 0, 0, TimeSpan.Zero),
                new DateTimeOffset(2026, 5, 18, 12, 0, 0, TimeSpan.Zero)),
            [ConversationGovernanceVerificationSuite.AuditPairing],
            new DateTimeOffset(2026, 5, 18, 12, 0, 0, TimeSpan.Zero),
            "correlation-001",
            ConversationGovernanceVerificationExecutionStatus.Completed,
            ConversationGovernanceVerificationFailureClassification.Passed,
            "Governance verification passed.",
            [
                new ConversationGovernanceVerificationCheckResultV1(
                    Version,
                    ConversationGovernanceVerificationSuite.AuditPairing,
                    "audit-pairing",
                    ["AC1", "AC5"],
                    ConversationGovernanceVerificationExecutionStatus.Completed,
                    ConversationGovernanceVerificationFailureClassification.Passed,
                    "Governed state has paired audit references.",
                    ConversationGovernanceVerificationRemediation.None,
                    new ConversationGovernanceVerificationEvidenceHandle("verification-proof-001")),
            ],
            AuditEvidence),
        GovernanceMetadata,
        GovernanceConversationTarget,
        SensitivityMessageTarget,
        new GovernanceTarget(GovernedTargetKind.AuditRecord, AuditEvidenceHandle: AuditEvidence.Handle),
        AuditEvidence.Handle,
        AuditEvidence,
        new AuditRecordPolicyTreatmentV1(
            Version,
            Tenant,
            Conversation,
            AuditEvidence.Handle,
            ProjectionTrustState.Current,
            ProjectionTrustState.Redacted,
            AuditRecordActionClassification.Allowed,
            ExportEligible: false,
            SeparateLogRequired: false,
            "retention-policy-standard",
            "Use the returned audit handle as governed evidence."),
        new GetConversationAuditRecordQuery(
            Version,
            Tenant,
            "caller-001",
            "correlation-001",
            Conversation,
            "audit-evidence-001",
            AuditRecordActionClassification.Allowed),
        new ConversationAuditRecordDetailsV1(
            Version,
            Tenant,
            Conversation,
            Actor,
            GovernanceTimestamp,
            AuditRecordActionClassification.Allowed,
            GovernanceOutcome.Succeeded,
            "retention-policy-standard",
            "customer-request",
            new GovernanceTarget(GovernedTargetKind.AuditRecord, AuditEvidenceHandle: AuditEvidence.Handle),
            AuditEvidence,
            new AuditRecordPolicyTreatmentV1(
                Version,
                Tenant,
                Conversation,
                AuditEvidence.Handle,
                ProjectionTrustState.Current,
                ProjectionTrustState.Redacted,
                AuditRecordActionClassification.Allowed,
                ExportEligible: false,
                SeparateLogRequired: false,
                "retention-policy-standard",
                "Use the returned audit handle as governed evidence."),
            FreshnessV1,
            ProjectionTrustState.Current,
            ProjectionFreshnessReasonCode.Current,
            "correlation-001",
            "causation-001"),
        ConversationAuditRecordResult.Visible(
            Version,
            new ConversationAuditRecordDetailsV1(
                Version,
                Tenant,
                Conversation,
                Actor,
                GovernanceTimestamp,
                AuditRecordActionClassification.Allowed,
                GovernanceOutcome.Succeeded,
                "retention-policy-standard",
                "customer-request",
                new GovernanceTarget(GovernedTargetKind.AuditRecord, AuditEvidenceHandle: AuditEvidence.Handle),
                AuditEvidence,
                new AuditRecordPolicyTreatmentV1(
                    Version,
                    Tenant,
                    Conversation,
                    AuditEvidence.Handle,
                    ProjectionTrustState.Current,
                    ProjectionTrustState.Redacted,
                    AuditRecordActionClassification.Allowed,
                    ExportEligible: false,
                    SeparateLogRequired: false,
                    "retention-policy-standard",
                    "Use the returned audit handle as governed evidence."),
                FreshnessV1,
                ProjectionTrustState.Current,
                ProjectionFreshnessReasonCode.Current,
                "correlation-001",
                "causation-001"),
            "Use the returned audit handle as governed evidence."),
        PrivilegedJustification,
        new RecordPrivilegedOperationalJustificationCommand(PrivilegedJustification),
        new GetPrivilegedOperationalJustificationQuery(
            Version,
            Tenant,
            "caller-001",
            "correlation-001",
            Conversation,
            "audit-evidence-001"),
        new PrivilegedOperationalJustificationDetailsV1(
            Version,
            Tenant,
            Conversation,
            GovernanceConversationTarget,
            Actor,
            PrivilegedOperationalActionClass.Read,
            PrivilegedActionClass.ComplianceReview,
            "privileged-review-policy",
            "customer-request",
            GovernanceTimestamp,
            GovernanceOutcome.Succeeded,
            AuditEvidence,
            ProjectionTrustState.Current,
            FreshnessV1,
            "Use the returned audit handle as governed evidence.",
            "correlation-001",
            "causation-001"),
        PrivilegedOperationalJustificationResult.Visible(
            Version,
            new PrivilegedOperationalJustificationDetailsV1(
                Version,
                Tenant,
                Conversation,
                GovernanceConversationTarget,
                Actor,
                PrivilegedOperationalActionClass.Read,
                PrivilegedActionClass.ComplianceReview,
                "privileged-review-policy",
                "customer-request",
                GovernanceTimestamp,
                GovernanceOutcome.Succeeded,
                AuditEvidence,
                ProjectionTrustState.Current,
                FreshnessV1,
                "Use the returned audit handle as governed evidence.",
                "correlation-001",
                "causation-001"),
            "Use the returned audit handle as governed evidence."),
        GovernanceRequest,
        GovernanceEvidence(GovernanceOperationKind.SetRetentionPolicy, GovernanceOutcome.Succeeded),
        RetentionCommand,
        SensitivityCommand,
        RedactionCommand,
        new ConversationRetentionPolicyResult(
            Version,
            Tenant,
            Conversation,
            GovernanceOutcome.Succeeded,
            "correlation-001",
            AuditEvidence,
            Remediation: GovernanceRemediation.None),
        new ConversationRetentionPolicyResult(
            Version,
            Tenant,
            Conversation,
            GovernanceOutcome.Denied,
            "correlation-002",
            Error: SafeError(ConversationErrorCode.TenantIsolationViolation),
            Remediation: GovernanceRemediation.ResubmitWithPolicyReference),
        new ConversationRetentionPolicyResult(
            Version,
            Tenant,
            Conversation,
            GovernanceOutcome.AuditUnavailableFailed,
            "correlation-003",
            Error: SafeError(ConversationErrorCode.AuditSinkUnavailable),
            Remediation: GovernanceRemediation.RetryWhenAuditAvailable),
        new ConversationRetentionPolicyResult(
            Version,
            Tenant,
            Conversation,
            GovernanceOutcome.PolicyBlocked,
            "correlation-004",
            Error: SafeError(ConversationErrorCode.CommandValidationFailed),
            Remediation: GovernanceRemediation.WaitForLegalHoldRelease),
        new ConversationSensitivityMarkResult(
            Version,
            Tenant,
            Conversation,
            SensitivityMessageTarget,
            SensitivityCategory.Restricted,
            GovernanceOutcome.Succeeded,
            "correlation-001",
            AuditEvidence,
            Remediation: GovernanceRemediation.None),
        new ConversationSensitivityMarkResult(
            Version,
            Tenant,
            Conversation,
            SensitivityMessageTarget,
            null,
            GovernanceOutcome.Denied,
            "correlation-002",
            Error: SafeError(ConversationErrorCode.TenantIsolationViolation),
            Remediation: GovernanceRemediation.RequestAuthorization),
        new ConversationSensitivityMarkResult(
            Version,
            Tenant,
            Conversation,
            SensitivityMessageTarget,
            null,
            GovernanceOutcome.AuditUnavailableFailed,
            "correlation-003",
            Error: SafeError(ConversationErrorCode.AuditSinkUnavailable),
            Remediation: GovernanceRemediation.RetryWhenAuditAvailable),
        new ConversationSensitivityMarkResult(
            Version,
            Tenant,
            Conversation,
            SensitivityMessageTarget,
            null,
            GovernanceOutcome.PolicyBlocked,
            "correlation-004",
            Error: SafeError(ConversationErrorCode.CommandValidationFailed),
            Remediation: GovernanceRemediation.WaitForLegalHoldRelease),
        new ConversationRedactionResult(
            Version,
            Tenant,
            Conversation,
            RedactionMessageTarget,
            RedactionCategory.ContentSuppression,
            GovernanceOutcome.Succeeded,
            "correlation-001",
            AuditEvidence,
            Remediation: GovernanceRemediation.None),
        new ConversationRedactionResult(
            Version,
            Tenant,
            Conversation,
            RedactionMessageTarget,
            null,
            GovernanceOutcome.Denied,
            "correlation-002",
            Error: SafeError(ConversationErrorCode.TenantIsolationViolation),
            Remediation: GovernanceRemediation.RequestAuthorization),
        new ConversationRedactionResult(
            Version,
            Tenant,
            Conversation,
            RedactionMessageTarget,
            null,
            GovernanceOutcome.AuditUnavailableFailed,
            "correlation-003",
            Error: SafeError(ConversationErrorCode.AuditSinkUnavailable),
            Remediation: GovernanceRemediation.RetryWhenAuditAvailable),
        new ConversationRedactionResult(
            Version,
            Tenant,
            Conversation,
            RedactionMessageTarget,
            null,
            GovernanceOutcome.PolicyBlocked,
            "correlation-004",
            Error: SafeError(ConversationErrorCode.CommandValidationFailed),
            Remediation: GovernanceRemediation.WaitForLegalHoldRelease),
        new ConversationRetentionPolicyProjectionV1(
            "retention-policy-standard",
            "customer-request",
            Actor,
            GovernanceTimestamp,
            AuditEvidence),
        new ConversationSensitivityMarkProjectionV1(
            SensitivityMessageTarget,
            SensitivityCategory.Restricted,
            "sensitivity-policy-standard",
            "customer-request",
            Actor,
            GovernanceTimestamp,
            AuditEvidence,
            ProjectionTrustState.Current),
        new ConversationRedactionProjectionV1(
            RedactionMessageTarget,
            RedactionCategory.ContentSuppression,
            "redaction-policy-standard",
            "customer-request",
            Actor,
            GovernanceTimestamp,
            AuditEvidence,
            ProjectionTrustState.Current),
        new CreateConversationCommand(CommandMetadata, Business, Project, Folder, "Case 123", ProviderCorrelation, Caller),
        new AppendMessageCommand(CommandMetadata, Conversation, Message, Actor, "Hello from the adopter.", ProviderCorrelation, Caller),
        new AddParticipantCommand(CommandMetadata, Conversation, Participant, ParticipantType.Human, ParticipantRole.Member, ProviderCorrelation),
        new AttachFileReferenceCommand(CommandMetadata, Conversation, File, Folder, Message),
        new UpdateConversationMetadataCommand(CommandMetadata, Conversation, "Case 123", Business, new Dictionary<string, string> { ["priority"] = "normal" }, Caller),
        new CloseConversationCommand(CommandMetadata, Conversation, "resolved"),
        new ArchiveConversationCommand(CommandMetadata, Conversation, "retained"),
        EventMetadata,
        new ConversationCreated(EventMetadata, Business, Project, Folder, "Case 123", ProviderCorrelation),
        new MessageAppended(EventMetadata, Message, Actor, "Hello from the adopter.", ProviderCorrelation),
        new ParticipantAdded(ParticipantEventMetadata, Participant, ParticipantType.Human, ParticipantRole.Member),
        new FileReferenceAttached(EventMetadata, File, Folder, Message),
        new ConversationMetadataUpdated(EventMetadata, "Case 123", Business, new Dictionary<string, string> { ["priority"] = "normal" }),
        new ConversationClosed(EventMetadata, "resolved"),
        new ConversationArchived(EventMetadata, "retained"),
        new ConversationLifecycleChanged(
            LifecycleChangedEventMetadata,
            ConversationLifecycleStatus.Open,
            ConversationLifecycleStatus.Closed,
            "resolved"),
        new RetentionPolicySet(
            RetentionSetEventMetadata,
            "retention-policy-standard",
            "customer-request",
            AuditEvidence),
        new RetentionPolicyReplaced(
            RetentionReplacedEventMetadata,
            "retention-policy-extended",
            "retention-policy-standard",
            "customer-request",
            AuditEvidence),
        new ConversationContentMarkedSensitive(
            SensitivityMarkedEventMetadata,
            SensitivityMessageTarget,
            SensitivityCategory.Restricted,
            "sensitivity-policy-standard",
            "customer-request",
            AuditEvidence),
        new MessageContentRedacted(
            RedactionEventMetadata,
            RedactionMessageTarget,
            RedactionCategory.ContentSuppression,
            "redaction-policy-standard",
            "customer-request",
            AuditEvidence),
        ProjectionTrustState.Current,
        ProjectionFreshnessReasonCode.Current,
        Freshness,
        FreshnessV1,
        new GetConversationQuery(Version, Tenant, "caller-001", "correlation-001", Conversation),
        new ConversationTemporalAnchorV1(
            Version,
            Tenant,
            Conversation,
            ConversationTemporalAnchorV1.SafeSourcePositionKind,
            SafeSourcePosition: 42),
        new GetConversationAtPointInTimeQuery(
            Version,
            Tenant,
            "caller-001",
            "correlation-001",
            Conversation,
            new ConversationTemporalAnchorV1(
                Version,
                Tenant,
                Conversation,
                ConversationTemporalAnchorV1.ProjectionCursorKind,
                ProjectionCursor: "pos:0000000042")),
        new ConversationTemporalConfidenceV1(
            Version,
            ProjectionTrustState.Current,
            ProjectionFreshnessReasonCode.Current,
            true,
            "Temporal evidence is complete for the requested anchor."),
        new ConversationTemporalDetailsV1(
            Version,
            Tenant,
            Conversation,
            new ConversationTemporalAnchorV1(
                Version,
                Tenant,
                Conversation,
                ConversationTemporalAnchorV1.SafeSourcePositionKind,
                SafeSourcePosition: 42),
            new ConversationTemporalConfidenceV1(
                Version,
                ProjectionTrustState.Current,
                ProjectionFreshnessReasonCode.Current,
                true,
                "Temporal evidence is complete for the requested anchor."),
            FreshnessV1,
            "Open",
            "Case 123",
            Messages:
            [
                new ConversationTimelineMessageProjectionV1(
                    Message,
                    Actor,
                    "[redacted]",
                    EventMetadata.CommittedAt),
            ],
            Redactions:
            [
                new ConversationRedactionProjectionV1(
                    RedactionMessageTarget,
                    RedactionCategory.ContentSuppression,
                    "redaction-policy-standard",
                    "customer-request",
                    Actor,
                    GovernanceTimestamp,
                    AuditEvidence,
                    ProjectionTrustState.Current),
            ]),
        ConversationCitationAvailability.Available,
        ConversationAuditReadinessState.Ready,
        ConversationVerificationState.Verified,
        ConversationSearchMatchSource.BusinessReference,
        new ConversationSearchTrustPreviewV1(
            ProjectionTrustState.Current,
            ProjectionFreshnessReasonCode.Current,
            ProjectionTrustState.Redacted,
            ProjectionTrustState.Current,
            ConversationCitationAvailability.Available,
            ConversationAuditReadinessState.Ready,
            ConversationVerificationState.Verified,
            ConversationSearchMatchSource.BusinessReference,
            "Visible through authorized tenant scope and matched business reference."),
        new ConversationCommandAvailabilityV1(
            "read-governed-record",
            ProjectionTrustState.Unavailable,
            "conversations.read",
            ProjectionTrustState.Current,
            "read",
            ProjectionTrustState.Current,
            ConversationAuditReadinessState.Ready,
            "Command execution is outside this read surface.",
            EventMetadata.CommittedAt),
        new ConversationEvidenceTrustPostureV1(
            Version,
            Tenant,
            Conversation,
            FreshnessV1.ProjectionCursor,
            FreshnessV1,
            ProjectionTrustState.Current,
            ProjectionTrustState.Current,
            ConversationCitationAvailability.Available,
            ConversationAuditReadinessState.Ready,
            ConversationVerificationState.Verified),
        new ConversationEvidenceEntryV1(
            "message:message-001",
            "Message",
            Actor,
            EventMetadata.CommittedAt,
            ProjectionTrustState.Current,
            ConversationCitationAvailability.Available,
            ConversationAuditReadinessState.Ready,
            ProjectionTrustState.Current,
            MessageId: Message,
            VisibleText: "Hello from the adopter."),
        new ConversationRedactionAttributionV1(
            RedactionCategory.ContentSuppression,
            "redaction-policy-standard",
            "customer-request",
            Actor,
            GovernanceTimestamp,
            RedactionMessageTarget,
            RedactionMessageTarget.ToTargetKey(),
            AuditEvidence,
            ConversationAuditReadinessState.Ready,
            ProjectionTrustState.Redacted,
            "[redacted]",
            "Redaction attribution",
            "Redacted evidence with governed attribution",
            "Open governed audit detail when authorized."),
        new ConversationListFilterV1(Business, Project, Folder, "Open", ParticipantPartyId: Participant),
        new ConversationPageRequest(25),
        new ConversationPageMetadata(1, "opaque-cursor"),
        new ListConversationsQuery(
            Version,
            Tenant,
            "caller-001",
            "correlation-001",
            new ConversationListFilterV1(Business, Project, Folder, "Open", ParticipantPartyId: Participant),
            new ConversationPageRequest(25)),
        new ConversationProviderCorrelationV1("provider-a", "assistant", Version),
        new ConversationParticipantProjectionV1(Participant, ParticipantType.Human, ParticipantRole.Member),
        new ConversationTimelineMessageProjectionV1(Message, Actor, "Hello from the adopter.", EventMetadata.CommittedAt, ProviderCorrelation),
        new ConversationFileReferenceProjectionV1(File, Folder, Message),
        new PartyReferenceHydrationV1(Participant, ProjectionTrustState.Current, true, "Project participant", "participant-token", "Available"),
        new ProjectReferenceHydrationV1(Project, ProjectionTrustState.Unavailable, false, "Reference unavailable", "unavailable", "Unavailable"),
        new FolderReferenceHydrationV1(Folder, ProjectionTrustState.Redacted, false, "Reference redacted", "redacted", "Redacted"),
        new FileReferenceHydrationV1(File, ProjectionTrustState.Forbidden, false, "Reference unavailable", "unavailable", "Unavailable"),
        new ConversationSummaryProjection(Tenant, Conversation, Freshness, "Case 123", Business, [Actor, Participant]),
        new ConversationSummaryProjectionV1(
            Version,
            Tenant,
            Conversation,
            FreshnessV1,
            "Open",
            "Case 123",
            Business,
            Project,
            Folder,
            [Actor, Participant],
            1,
            1,
            ProviderCorrelation),
        new ConversationDetailProjectionV1(
            Version,
            Tenant,
            Conversation,
            FreshnessV1,
            "Open",
            "Case 123",
            Business,
            Project,
            Folder,
            ProviderCorrelation,
            [new ConversationParticipantProjectionV1(Participant, ParticipantType.Human, ParticipantRole.Member)],
            [new ConversationTimelineMessageProjectionV1(Message, Actor, "Hello from the adopter.", EventMetadata.CommittedAt, ProviderCorrelation)],
            [new ConversationFileReferenceProjectionV1(File, Folder, Message)],
            new Dictionary<string, string> { ["priority"] = "normal" },
            new ConversationRetentionPolicyProjectionV1(
                "retention-policy-standard",
                "customer-request",
                Actor,
                GovernanceTimestamp,
                AuditEvidence),
            [
                new ConversationSensitivityMarkProjectionV1(
                    SensitivityMessageTarget,
                    SensitivityCategory.Restricted,
                    "sensitivity-policy-standard",
                    "customer-request",
                    Actor,
                    GovernanceTimestamp,
                    AuditEvidence,
                    ProjectionTrustState.Current),
            ]),
        new ConversationSummaryV1(
            Version,
            Tenant,
            Conversation,
            FreshnessV1,
            "Open",
            "Case 123",
            Business,
            Project,
            Folder,
            [Actor, Participant],
            1,
            1,
            new ConversationProviderCorrelationV1("provider-a", "assistant", Version)),
        new ConversationDetailsV1(
            Version,
            Tenant,
            Conversation,
            FreshnessV1,
            "Open",
            "Case 123",
            Business,
            Project,
            Folder,
            new ConversationProviderCorrelationV1("provider-a", "assistant", Version),
            [new ConversationParticipantProjectionV1(Participant, ParticipantType.Human, ParticipantRole.Member)],
            [new ConversationTimelineMessageProjectionV1(Message, Actor, "Hello from the adopter.", EventMetadata.CommittedAt)],
            [new ConversationFileReferenceProjectionV1(File, Folder, Message)],
            "Unavailable",
            PartyHydration: [new PartyReferenceHydrationV1(Participant, ProjectionTrustState.Current, true, "Project participant", "participant-token", "Available")],
            ProjectHydration: new ProjectReferenceHydrationV1(Project, ProjectionTrustState.Unavailable, false, "Reference unavailable", "unavailable", "Unavailable"),
            FolderHydration: new FolderReferenceHydrationV1(Folder, ProjectionTrustState.Redacted, false, "Reference redacted", "redacted", "Redacted"),
            FileHydration: [new FileReferenceHydrationV1(File, ProjectionTrustState.Forbidden, false, "Reference unavailable", "unavailable", "Unavailable")]),
        ConversationDetailResult.Visible(
            Version,
            new ConversationDetailsV1(
                Version,
                Tenant,
                Conversation,
                FreshnessV1,
                "Open",
                "Case 123",
                Business,
                Project,
                Folder,
                new ConversationProviderCorrelationV1("provider-a", "assistant", Version),
                [new ConversationParticipantProjectionV1(Participant, ParticipantType.Human, ParticipantRole.Member)],
                [new ConversationTimelineMessageProjectionV1(Message, Actor, "Hello from the adopter.", EventMetadata.CommittedAt)],
                [new ConversationFileReferenceProjectionV1(File, Folder, Message)],
                "Unavailable",
                PartyHydration: [new PartyReferenceHydrationV1(Participant, ProjectionTrustState.Current, true, "Project participant", "participant-token", "Available")],
                SensitivityMarks:
                [
                    new ConversationSensitivityMarkProjectionV1(
                        SensitivityMessageTarget,
                        SensitivityCategory.Restricted,
                        "sensitivity-policy-standard",
                        "customer-request",
                        Actor,
                        GovernanceTimestamp,
                        AuditEvidence,
                        ProjectionTrustState.Current),
                ],
                Redactions:
                [
                    new ConversationRedactionProjectionV1(
                        RedactionMessageTarget,
                        RedactionCategory.ContentSuppression,
                        "redaction-policy-standard",
                        "customer-request",
                        Actor,
                        GovernanceTimestamp,
                        AuditEvidence,
                        ProjectionTrustState.Current),
                ]),
            "Current projection is available."),
        ConversationTemporalDetailResult.Visible(
            Version,
            new ConversationTemporalDetailsV1(
                Version,
                Tenant,
                Conversation,
                new ConversationTemporalAnchorV1(
                    Version,
                    Tenant,
                    Conversation,
                    ConversationTemporalAnchorV1.SafeSourcePositionKind,
                    SafeSourcePosition: 42),
                new ConversationTemporalConfidenceV1(
                    Version,
                    ProjectionTrustState.Current,
                    ProjectionFreshnessReasonCode.Current,
                    true,
                    "Temporal evidence is complete for the requested anchor."),
                FreshnessV1,
                "Open",
                "Case 123",
                Messages:
                [
                    new ConversationTimelineMessageProjectionV1(
                        Message,
                        Actor,
                        "[redacted]",
                        EventMetadata.CommittedAt),
                ],
                Redactions:
                [
                    new ConversationRedactionProjectionV1(
                        RedactionMessageTarget,
                        RedactionCategory.ContentSuppression,
                        "redaction-policy-standard",
                        "customer-request",
                        Actor,
                        GovernanceTimestamp,
                        AuditEvidence,
                        ProjectionTrustState.Current),
                ]),
            "Use the returned temporal anchor for stable historical evidence."),
        new ConversationCitationTargetV1(
            Version,
            Tenant,
            Conversation,
            "message:message-001"),
        new GetConversationCitationQuery(
            Version,
            Tenant,
            "caller-001",
            "correlation-001",
            Conversation,
            "message:message-001"),
        new ConversationCitationV1(
            Version,
            Tenant,
            Conversation,
            "message:message-001",
            "Message",
            EventMetadata.CommittedAt,
            ProjectionTrustState.Current,
            ConversationCitationAvailability.Available,
            ConversationAuditReadinessState.Ready,
            Actor,
            AuditEvidence,
            FreshnessV1.ProjectionCursor,
            FreshnessV1.LastAppliedEventPosition,
            "temporal:v1:pos:0000000042:projection:0000000042",
            "citation=conversation-001/message:message-001; tenant=tenant:tenant-001; evidence=message:message-001",
            "Message evidence citation",
            "Copy message evidence citation",
            "Open stable temporal evidence link."),
        ConversationCitationResult.Visible(
            Version,
            new ConversationCitationV1(
                Version,
                Tenant,
                Conversation,
                "message:message-001",
                "Message",
                EventMetadata.CommittedAt,
                ProjectionTrustState.Current,
                ConversationCitationAvailability.Available,
                ConversationAuditReadinessState.Ready,
                Actor,
                AuditEvidence,
                FreshnessV1.ProjectionCursor,
                FreshnessV1.LastAppliedEventPosition,
                "temporal:v1:pos:0000000042:projection:0000000042",
                "citation=conversation-001/message:message-001; tenant=tenant:tenant-001; evidence=message:message-001",
                "Message evidence citation",
                "Copy message evidence citation",
                "Open stable temporal evidence link."),
            "Use the copied citation text only for governed evidence references."),
        new ConversationListResult(
            Version,
            ProjectionTrustState.Current,
            ProjectionFreshnessReasonCode.Current,
            [
                new ConversationSummaryV1(
                    Version,
                    Tenant,
                    Conversation,
                    FreshnessV1,
                    "Open",
                    "Case 123",
                    Business,
                    Project,
                    Folder,
                    [Actor, Participant],
                    1,
                    1,
                    new ConversationProviderCorrelationV1("provider-a", "assistant", Version)),
            ],
            new ConversationPageMetadata(1),
            "Accessible results are complete for the supplied filters."),
        new ConversationMessageProjection(Tenant, Conversation, Message, Actor, "Hello from the adopter.", EventMetadata.CommittedAt, Freshness),
        Visibility,
        new ConversationCommandAcceptedResult(Version, Tenant, Conversation, ConversationCommandType.AppendMessageCommand, "correlation-001", "idempotency-001", Visibility),
        new ConversationCreatedResult(Version, Tenant, Conversation, "correlation-001", "idempotency-001", Visibility, ConversationCommandType.CreateConversationCommand),
        SafeError(ConversationErrorCode.TenantIsolationViolation),
        new ConversationErrorResult([SafeError(ConversationErrorCode.AggregateNotFound)]),
    ];

    internal static GovernanceAuditEvidence GovernanceEvidence(GovernanceOperationKind operationKind, GovernanceOutcome outcome)
        => new(
            GovernanceMetadata,
            operationKind,
            GovernanceConversationTarget,
            outcome,
            AuditEvidence,
            RemediationFor(outcome));

    private static GovernanceRemediation RemediationFor(GovernanceOutcome outcome)
    {
        if (outcome == GovernanceOutcome.Denied)
        {
            return GovernanceRemediation.ResubmitWithPolicyReference;
        }

        if (outcome == GovernanceOutcome.AuditUnavailableFailed)
        {
            return GovernanceRemediation.RetryWhenAuditAvailable;
        }

        if (outcome == GovernanceOutcome.PolicyBlocked)
        {
            return GovernanceRemediation.WaitForLegalHoldRelease;
        }

        return GovernanceRemediation.None;
    }

    internal static ConversationError SafeError(ConversationErrorCode code) => ConversationErrorCatalog.CreateError(
        code,
        "correlation-001",
        auditHandle: "audit-001",
        safeFieldDiagnostics: new Dictionary<string, string>
        {
            ["target"] = "hidden",
        },
        developerGuidance: "The requested operation was not accepted.");

    internal static IReadOnlyList<ConversationErrorCode> AllErrorCodes =>
    [
        ConversationErrorCode.TenantBindingMissing,
        ConversationErrorCode.TenantIsolationViolation,
        ConversationErrorCode.TenantProjectionStale,
        ConversationErrorCode.AuditSinkUnavailable,
        ConversationErrorCode.AuditPairingRequired,
        ConversationErrorCode.IdempotencyConflict,
        ConversationErrorCode.IdempotencyOutcomeUnknown,
        ConversationErrorCode.IdempotencyKeyMissing,
        ConversationErrorCode.AggregateNotFound,
        ConversationErrorCode.SchemaVersionUnsupported,
        ConversationErrorCode.CommandValidationFailed,
        ConversationErrorCode.DuplicateParticipant,
        ConversationErrorCode.UnsupportedParticipant,
        ConversationErrorCode.ParticipantValidationUnavailable,
        ConversationErrorCode.TenantContextMismatch,
        ConversationErrorCode.ProviderOnlyIdentityForbidden,
    ];

}
