// <copyright file="ConversationsJsonContext.cs" company="ITANEO">
// Copyright (c) ITANEO. All rights reserved.
// Licensed under the MIT License.
// </copyright>

using System.Text.Json;
using System.Text.Json.Serialization;

using Hexalith.Conversations.Contracts.Commands;
using Hexalith.Conversations.Contracts.Conformance;
using Hexalith.Conversations.Contracts.Diagnostics;
using Hexalith.Conversations.Contracts.Errors;
using Hexalith.Conversations.Contracts.Events;
using Hexalith.Conversations.Contracts.Governance;
using Hexalith.Conversations.Contracts.Identifiers;
using Hexalith.Conversations.Contracts.Participants;
using Hexalith.Conversations.Contracts.Projections;
using Hexalith.Conversations.Contracts.Queries;
using Hexalith.Conversations.Contracts.Results;
using Hexalith.Conversations.Contracts.TrustStates;
using Hexalith.Conversations.Contracts.Versioning;

namespace Hexalith.Conversations.Contracts.Serialization;

/// <summary>
/// Source-generated JSON metadata for the public Conversations contract surface.
/// </summary>
[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(AddParticipantCommand))]
[JsonSerializable(typeof(AppendMessageCommand))]
[JsonSerializable(typeof(ArchiveConversationCommand))]
[JsonSerializable(typeof(AttachFileReferenceCommand))]
[JsonSerializable(typeof(CloseConversationCommand))]
[JsonSerializable(typeof(ConversationCommandMetadata))]
[JsonSerializable(typeof(ConversationProjectAssignment))]
[JsonSerializable(typeof(ConversationProjectAssignmentOperation))]
[JsonSerializable(typeof(CreateConversationCommand))]
[JsonSerializable(typeof(ReassignConversationProjectCommand))]
[JsonSerializable(typeof(UpdateConversationMetadataCommand))]
[JsonSerializable(typeof(BuyerAcceptanceItemStatus))]
[JsonSerializable(typeof(BuyerPartialAcceptanceItemV1))]
[JsonSerializable(typeof(CapabilityReleaseScope))]
[JsonSerializable(typeof(CapabilityReleaseScopeEntryV1))]
[JsonSerializable(typeof(ConformanceCheck))]
[JsonSerializable(typeof(ConformanceCheckResultV1))]
[JsonSerializable(typeof(ConformanceFailureClassification))]
[JsonSerializable(typeof(ConformanceManifestChangeV1))]
[JsonSerializable(typeof(ConformanceManifestLifecycleStage))]
[JsonSerializable(typeof(ConformanceManifestRowV1))]
[JsonSerializable(typeof(ConformanceManifestV1))]
[JsonSerializable(typeof(ConformanceOutcome))]
[JsonSerializable(typeof(ConformanceRunResultV1))]
[JsonSerializable(typeof(ReleaseConformanceArtifactV1))]
[JsonSerializable(typeof(ReleaseGateId))]
[JsonSerializable(typeof(ReleaseGateResultV1))]
[JsonSerializable(typeof(ReleaseGateStatus))]
[JsonSerializable(typeof(ReleaseWaiverV1))]
[JsonSerializable(typeof(SecondAdopterStatus))]
[JsonSerializable(typeof(SecondAdopterStatusEntryV1))]
[JsonSerializable(typeof(SubstrateConsequenceArea))]
[JsonSerializable(typeof(WaiverLifecycleStatus))]
[JsonSerializable(typeof(CorePreconditionV1))]
[JsonSerializable(typeof(OnboardingDiagnosticCheck))]
[JsonSerializable(typeof(OnboardingDiagnosticCheckResultV1))]
[JsonSerializable(typeof(OnboardingDiagnosticRunResultV1))]
[JsonSerializable(typeof(OnboardingDiagnosticStatus))]
[JsonSerializable(typeof(ConversationError))]
[JsonSerializable(typeof(ConversationErrorCategory))]
[JsonSerializable(typeof(ConversationErrorClientAction))]
[JsonSerializable(typeof(ConversationErrorCode))]
[JsonSerializable(typeof(ConversationErrorDescriptor))]
[JsonSerializable(typeof(ConversationErrorResult))]
[JsonSerializable(typeof(ConversationArchived))]
[JsonSerializable(typeof(ConversationClosed))]
[JsonSerializable(typeof(ConversationContentMarkedSensitive))]
[JsonSerializable(typeof(ConversationCreated))]
[JsonSerializable(typeof(ConversationEventMetadata))]
[JsonSerializable(typeof(ConversationEventType))]
[JsonSerializable(typeof(ConversationLifecycleChanged))]
[JsonSerializable(typeof(ConversationLifecycleStatus))]
[JsonSerializable(typeof(ConversationMetadataUpdated))]
[JsonSerializable(typeof(ConversationProjectChanged))]
[JsonSerializable(typeof(FileReferenceAttached))]
[JsonSerializable(typeof(MessageAppended))]
[JsonSerializable(typeof(MessageContentRedacted))]
[JsonSerializable(typeof(ParticipantAdded))]
[JsonSerializable(typeof(RetentionPolicyReplaced))]
[JsonSerializable(typeof(RetentionPolicySet))]
[JsonSerializable(typeof(AuditEvidenceHandle))]
[JsonSerializable(typeof(AuditRecordActionClassification))]
[JsonSerializable(typeof(AuditRecordPolicyTreatmentV1))]
[JsonSerializable(typeof(BuyerAcceptanceDemoExecutionStatus))]
[JsonSerializable(typeof(BuyerAcceptanceDemoFixtureKind))]
[JsonSerializable(typeof(BuyerAcceptanceDemoFixtureV1))]
[JsonSerializable(typeof(BuyerAcceptanceDemoScenarioV1))]
[JsonSerializable(typeof(BuyerAcceptanceDemoStepKind))]
[JsonSerializable(typeof(BuyerAcceptanceDemoStepV1))]
[JsonSerializable(typeof(BuyerAcceptanceDemoTrustState))]
[JsonSerializable(typeof(BuyerAcceptanceEvidenceOwnership))]
[JsonSerializable(typeof(BuyerAcceptanceEvidenceStepResultV1))]
[JsonSerializable(typeof(BuyerAcceptanceEvidenceSummaryV1))]
[JsonSerializable(typeof(BuyerAcceptanceVerificationSummaryV1))]
[JsonSerializable(typeof(ConversationGovernanceVerificationCheckResultV1))]
[JsonSerializable(typeof(ConversationGovernanceVerificationEvidenceHandle))]
[JsonSerializable(typeof(ConversationGovernanceVerificationExecutionStatus))]
[JsonSerializable(typeof(ConversationGovernanceVerificationFailureClassification))]
[JsonSerializable(typeof(ConversationGovernanceVerificationRemediation))]
[JsonSerializable(typeof(ConversationGovernanceVerificationRequestV1))]
[JsonSerializable(typeof(ConversationGovernanceVerificationRunResultV1))]
[JsonSerializable(typeof(ConversationGovernanceVerificationScopeKind))]
[JsonSerializable(typeof(ConversationGovernanceVerificationScopeV1))]
[JsonSerializable(typeof(ConversationGovernanceVerificationSuite))]
[JsonSerializable(typeof(ConversationRedactionResult))]
[JsonSerializable(typeof(ConversationRetentionPolicyResult))]
[JsonSerializable(typeof(ConversationSensitivityMarkResult))]
[JsonSerializable(typeof(GovernanceAuditEvidence))]
[JsonSerializable(typeof(GovernanceAuditEvidenceReference))]
[JsonSerializable(typeof(GovernanceOperationMetadata))]
[JsonSerializable(typeof(GovernanceRequest))]
[JsonSerializable(typeof(GovernanceTarget))]
[JsonSerializable(typeof(GovernanceOperationKind))]
[JsonSerializable(typeof(GovernedTargetKind))]
[JsonSerializable(typeof(RetentionAction))]
[JsonSerializable(typeof(SensitivityCategory))]
[JsonSerializable(typeof(RedactionCategory))]
[JsonSerializable(typeof(ArchivalState))]
[JsonSerializable(typeof(LegalHoldDeferral))]
[JsonSerializable(typeof(PolicyBlockedOutcome))]
[JsonSerializable(typeof(PrivilegedActionClass))]
[JsonSerializable(typeof(PrivilegedOperationalActionClass))]
[JsonSerializable(typeof(GovernanceOutcome))]
[JsonSerializable(typeof(GovernanceRemediation))]
[JsonSerializable(typeof(GovernanceStateConcept))]
[JsonSerializable(typeof(MarkConversationContentSensitiveCommand))]
[JsonSerializable(typeof(PrivilegedOperationalJustificationV1))]
[JsonSerializable(typeof(RecordPrivilegedOperationalJustificationCommand))]
[JsonSerializable(typeof(RedactMessageContentCommand))]
[JsonSerializable(typeof(SetConversationRetentionPolicyCommand))]
[JsonSerializable(typeof(BusinessReference))]
[JsonSerializable(typeof(CallerMetadata))]
[JsonSerializable(typeof(ConversationId))]
[JsonSerializable(typeof(FileId))]
[JsonSerializable(typeof(FolderId))]
[JsonSerializable(typeof(MessageId))]
[JsonSerializable(typeof(PartyId))]
[JsonSerializable(typeof(ProjectId))]
[JsonSerializable(typeof(ProviderCorrelationMetadata))]
[JsonSerializable(typeof(TenantId))]
[JsonSerializable(typeof(ParticipantRole))]
[JsonSerializable(typeof(ParticipantType))]
[JsonSerializable(typeof(ConversationDetailProjectionV1))]
[JsonSerializable(typeof(ConversationFileReferenceProjectionV1))]
[JsonSerializable(typeof(ConversationMessageProjection))]
[JsonSerializable(typeof(ConversationParticipantProjectionV1))]
[JsonSerializable(typeof(ConversationRedactionProjectionV1))]
[JsonSerializable(typeof(ConversationRetentionPolicyProjectionV1))]
[JsonSerializable(typeof(ConversationSensitivityMarkProjectionV1))]
[JsonSerializable(typeof(ConversationSummaryProjection))]
[JsonSerializable(typeof(ConversationSummaryProjectionV1))]
[JsonSerializable(typeof(ConversationTimelineMessageProjectionV1))]
[JsonSerializable(typeof(ProjectionFreshness))]
[JsonSerializable(typeof(ProjectionFreshnessReasonCode))]
[JsonSerializable(typeof(ProjectionFreshnessV1))]
[JsonSerializable(typeof(ConversationAuditRecordDetailsV1))]
[JsonSerializable(typeof(ConversationAuditRecordResult))]
[JsonSerializable(typeof(ConversationCitationResult))]
[JsonSerializable(typeof(ConversationCitationTargetV1))]
[JsonSerializable(typeof(ConversationCitationV1))]
[JsonSerializable(typeof(ConversationCommandAvailabilityV1))]
[JsonSerializable(typeof(ConversationDetailResult))]
[JsonSerializable(typeof(ConversationDetailsV1))]
[JsonSerializable(typeof(ConversationEvidenceEntryV1))]
[JsonSerializable(typeof(ConversationEvidenceTrustPostureV1))]
[JsonSerializable(typeof(ConversationListFilterV1))]
[JsonSerializable(typeof(ConversationListResult))]
[JsonSerializable(typeof(ConversationPageMetadata))]
[JsonSerializable(typeof(ConversationPageRequest))]
[JsonSerializable(typeof(ConversationProviderCorrelationV1))]
[JsonSerializable(typeof(ConversationRedactionAttributionV1))]
[JsonSerializable(typeof(ConversationSearchTrustPreviewV1))]
[JsonSerializable(typeof(ConversationAuditReadinessState))]
[JsonSerializable(typeof(ConversationCitationAvailability))]
[JsonSerializable(typeof(ConversationSearchMatchSource))]
[JsonSerializable(typeof(ConversationVerificationState))]
[JsonSerializable(typeof(ConversationSummaryV1))]
[JsonSerializable(typeof(ConversationTemporalAnchorV1))]
[JsonSerializable(typeof(ConversationTemporalConfidenceV1))]
[JsonSerializable(typeof(ConversationTemporalDetailResult))]
[JsonSerializable(typeof(ConversationTemporalDetailsV1))]
[JsonSerializable(typeof(FileReferenceHydrationV1))]
[JsonSerializable(typeof(FolderReferenceHydrationV1))]
[JsonSerializable(typeof(GetConversationAtPointInTimeQuery))]
[JsonSerializable(typeof(GetConversationAuditRecordQuery))]
[JsonSerializable(typeof(GetConversationCitationQuery))]
[JsonSerializable(typeof(GetConversationQuery))]
[JsonSerializable(typeof(GetPrivilegedOperationalJustificationQuery))]
[JsonSerializable(typeof(ListConversationsQuery))]
[JsonSerializable(typeof(PartyReferenceHydrationV1))]
[JsonSerializable(typeof(PrivilegedOperationalJustificationDetailsV1))]
[JsonSerializable(typeof(PrivilegedOperationalJustificationResult))]
[JsonSerializable(typeof(ProjectReferenceHydrationV1))]
[JsonSerializable(typeof(ConversationCommandAcceptedResult))]
[JsonSerializable(typeof(ConversationCommandType))]
[JsonSerializable(typeof(ConversationCreatedResult))]
[JsonSerializable(typeof(ReadModelVisibility))]
[JsonSerializable(typeof(ProjectionTrustState))]
[JsonSerializable(typeof(ContractCompatibilityMetadata))]
[JsonSerializable(typeof(ContractCompatibilityRemediation))]
[JsonSerializable(typeof(ContractCompatibilityRequest))]
[JsonSerializable(typeof(ContractCompatibilityResult))]
[JsonSerializable(typeof(ContractCompatibilityStatus))]
[JsonSerializable(typeof(ContractPackageVersionInfo))]
[JsonSerializable(typeof(ContractVersionInfo))]
[JsonSerializable(typeof(UnsupportedSchemaVersion))]
[JsonSerializable(typeof(SchemaVersion))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(string[]))]
internal sealed partial class ConversationsJsonContext : JsonSerializerContext
{
}
